In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

In [2]:

#https://drive.google.com/file/d/1JSCQybUA36iZT7BW1aKdttS6wHw7h_RI/view?usp=drive_link

file_id = '1JSCQybUA36iZT7BW1aKdttS6wHw7h_RI'
link = f'https://drive.google.com/uc?id={file_id}'
data_s = pd.read_csv(link)
data_s

data_s.head()


R&D Spend  Administration  Marketing Spend    State     Profit
0  165349.20       136897.80        471784.10   Iloilo  192261.83
1  162597.70       151377.59        443898.53  Bacolod  191792.06
2  153441.51       101145.55        407934.54     Cebu  191050.39
3  144372.41       118671.85        383199.62      NaN  182901.99
4  142107.34        91391.77        366168.42   Iloilo  166187.94

In [3]:
data_s.isnull().sum()

R&D Spend          2
Administration     1
Marketing Spend    0
State              3
Profit             0
dtype: int64

In [4]:
data_s['R&D Spend'] = data_s['R&D Spend'].interpolate(method='linear')
data_s['Administration'] = data_s['Administration'].interpolate(method='linear')
data_s['State'].fillna(data_s['State'].mode()[0], inplace=True)

data_st = data_s
data_st

R&D Spend  Administration  Marketing Spend    State     Profit
0   165349.200       136897.80        471784.10   Iloilo  192261.83
1   162597.700       151377.59        443898.53  Bacolod  191792.06
2   153441.510       101145.55        407934.54     Cebu  191050.39
3   144372.410       118671.85        383199.62   Iloilo  182901.99
4   142107.340        91391.77        366168.42   Iloilo  166187.94
5   131876.900        99814.71        362861.36  Bacolod  156991.12
6   134615.460       147198.87        127716.82     Cebu  156122.51
7   130298.130       145530.06        323876.68   Makati  155752.60
8   120542.520       148718.95        311613.29   Iloilo  152211.77
9   123334.880       108679.17        304981.62   Iloilo  149759.96
10  112003.420       110594.11        229160.95     Cebu  146121.95
11  100671.960        91790.61        249744.55   Makati  144259.40
12   93863.750       127320.38        249839.44   Iloilo  141585.52
13   91992.390       135495.07        252664.93  Bacolod  134307.35
14  119943.240       156547.42        256512.92     Cebu  132602.65
15  114523.610       122616.84        261776.23   Makati  129917.04
16   78013.110       121597.55        264346.06   Iloilo  126992.93
17   94657.160       145077.58        282574.31  Bacolod  125370.37
18   91749.160       114175.79        294919.57     Cebu  124266.90
19   86419.700       153514.11             0.00   Makati  122776.86
20   76253.860       113867.30        298664.47   Iloilo  118474.03
21   78389.470       153773.43        299737.29  Bacolod  111313.02
22   73994.560       122782.75        303319.26     Cebu  110352.25
23   67532.530       105751.03        304768.73   Makati  108733.99
24   77044.010        99281.34        140574.81   Iloilo  108552.04
25   64664.710       139553.16        137962.62  Bacolod  107404.34
26   75328.870       144135.98        134050.07     Cebu  105733.54
27   72107.600       127864.55        353183.81   Makati  105008.31
28   66051.520       182645.56        118148.20   Iloilo  103282.38
29   65605.480       153032.06        107138.38  Bacolod  101004.64
30   61994.480       115641.28         91131.24     Cebu   99937.59
31   61136.380       152701.92         88218.23   Makati   97483.56
32   63408.860       129219.61         46085.25   Iloilo   97427.84
33   55493.950       103057.49        214634.81  Bacolod   96778.92
34   46426.070       157693.92        210797.67     Cebu   96712.80
35   46014.020        85047.44        205517.64   Makati   96479.51
36   45041.985       127056.21        201126.82   Iloilo   90708.19
37   44069.950        96502.07        197029.42  Bacolod   89949.14
38   20229.590        65947.93        185265.10     Cebu   81229.06
39   38558.510        82982.09        174999.30   Makati   81005.76
40   28754.330       118546.05        172795.67   Iloilo   78239.91
41   27892.920        84710.77        164470.71   Iloilo   77798.83
42   23640.930        96189.63        148001.11     Cebu   71498.49
43   15505.730       127382.30         35534.17   Makati   69758.98
44   22177.740       154806.14         28334.72   Iloilo   65200.33
45    1000.230       124153.04          1903.93  Bacolod   64926.08
46    1315.460       115816.21        297114.46     Cebu   49490.75
47       0.000       135426.92             0.00   Makati   42559.73
48     542.050        51743.15             0.00   Iloilo   35673.41
49       0.000       116983.80         45173.06  Bacolod   14681.40

In [6]:
x = data_st.iloc[:, :-1].values
y = data_st.iloc[:, -1].values

print("INDEPENDENT VARIABLE:\n", x)
print("DEPENDENT VARIABLE:\n", y)


INDEPENDENT VARIABLE:
 [[165349.2 136897.8 471784.1 'Iloilo']
 [162597.7 151377.59 443898.53 'Bacolod']
 [153441.51 101145.55 407934.54 'Cebu']
 [144372.41 118671.85 383199.62 'Iloilo']
 [142107.34 91391.77 366168.42 'Iloilo']
 [131876.9 99814.71 362861.36 'Bacolod']
 [134615.46 147198.87 127716.82 'Cebu']
 [130298.13 145530.06 323876.68 'Makati']
 [120542.52 148718.95 311613.29 'Iloilo']
 [123334.88 108679.17 304981.62 'Iloilo']
 [112003.42000000001 110594.11 229160.95 'Cebu']
 [100671.96 91790.61 249744.55 'Makati']
 [93863.75 127320.38 249839.44 'Iloilo']
 [91992.39 135495.07 252664.93 'Bacolod']
 [119943.24 156547.42 256512.92 'Cebu']
 [114523.61 122616.84 261776.23 'Makati']
 [78013.11 121597.55 264346.06 'Iloilo']
 [94657.16 145077.58 282574.31 'Bacolod']
 [91749.16 114175.79 294919.57 'Cebu']
 [86419.7 153514.11 0.0 'Makati']
 [76253.86 113867.3 298664.47 'Iloilo']
 [78389.47 153773.43 299737.29 'Bacolod']
 [73994.56 122782.75 303319.26 'Cebu']
 [67532.53 105751.03 304768.73 'Ma

In [7]:

categorical_columns = ['State']

categorical_indices = [data_s.columns.get_loc(col) for col in categorical_columns]

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(sparse=False), categorical_indices)
    ],
    remainder='passthrough'  # Keep the remaining columns as they are
)
x = ct.fit_transform(x)
x


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0.0, 0.0, 1.0, 0.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 0.0, 144372.41, 118671.85, 383199.62],
       [0.0, 0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1.0, 0.0, 0.0, 0.0, 131876.9, 99814.71, 362861.36],
       [0.0, 1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 0.0, 0.0, 1.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 0.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 1.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 0.0, 112003.42000000001, 110594.11, 229160.95],
       [0.0, 0.0, 0.0, 1.0, 100671.96, 91790.61, 249744.55],
       [0.0, 0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0

In [8]:
pd.DataFrame(x).head(12)

0    1    2    3          4          5          6
0   0.0  0.0  1.0  0.0   165349.2   136897.8   471784.1
1   1.0  0.0  0.0  0.0   162597.7  151377.59  443898.53
2   0.0  1.0  0.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  0.0  144372.41  118671.85  383199.62
4   0.0  0.0  1.0  0.0  142107.34   91391.77  366168.42
5   1.0  0.0  0.0  0.0   131876.9   99814.71  362861.36
6   0.0  1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  0.0  0.0  1.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  0.0  120542.52  148718.95  311613.29
9   0.0  0.0  1.0  0.0  123334.88  108679.17  304981.62
10  0.0  1.0  0.0  0.0  112003.42  110594.11  229160.95
11  0.0  0.0  0.0  1.0  100671.96   91790.61  249744.55

In [9]:
pd.DataFrame(y).head(12)

0
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state= 1)

print("X Train:\n",X_train)
print("X Test:\n",X_test)
print("Y Train:\n",y_train)
print("Y Test:\n",y_test)

X Train:
 [[0.0 0.0 1.0 0.0 63408.86 129219.61 46085.25]
 [0.0 0.0 0.0 1.0 38558.51 82982.09 174999.3]
 [1.0 0.0 0.0 0.0 78389.47 153773.43 299737.29]
 [0.0 0.0 1.0 0.0 45041.985 127056.21 201126.82]
 [0.0 0.0 0.0 1.0 86419.7 153514.11 0.0]
 [0.0 1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 0.0 0.0 116983.8 45173.06]
 [0.0 1.0 0.0 0.0 75328.87 144135.98 134050.07]
 [0.0 1.0 0.0 0.0 73994.56 122782.75 303319.26]
 [1.0 0.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [1.0 0.0 0.0 0.0 94657.16 145077.58 282574.31]
 [1.0 0.0 0.0 0.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 0.0 77044.01 99281.34 140574.81]
 [0.0 0.0 0.0 1.0 67532.53 105751.03 304768.73]
 [0.0 0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [1.0 0.0 0.0 0.0 55493.95 103057.49 214634.81]
 [0.0 1.0 0.0 0.0 119943.24 156547.42 256512.92]
 [0.0 1.0 0.0 0.0 61994.48 115641.28 91131.24]
 [0.0 1.0 0.0 0.0 112003.42000000001 110594.11 229160.95]
 [0.0 0.0 1.0 0.0 66051.52 182645.56 11814

In [11]:
from sklearn import metrics
import seaborn as seabornInstance
from sklearn.model_selection import train_test_split
from statsmodels.regression.linear_model import OLS

In [12]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [13]:
y_pred = pd.DataFrame()   # dataframe for predictions vs actual y-values
y_pred['predictions'] = model.predict(X_test)


print(model.predict(X_test))
y_pred

[113671.29227191  89670.79762675  76921.54451098  67071.7096238
 177373.64046375 173232.5405531   50750.15525607 100917.85478429
  54685.2692477   98344.14848891]


predictions
0  113671.292272
1   89670.797627
2   76921.544511
3   67071.709624
4  177373.640464
5  173232.540553
6   50750.155256
7  100917.854784
8   54685.269248
9   98344.148489

In [14]:
df = pd.DataFrame({"Actual": y[:10], "Predicted": y_pred['predictions'][:10]})
df

Actual      Predicted
0  192261.83  113671.292272
1  191792.06   89670.797627
2  191050.39   76921.544511
3  182901.99   67071.709624
4  166187.94  177373.640464
5  156991.12  173232.540553
6  156122.51   50750.155256
7  155752.60  100917.854784
8  152211.77   54685.269248
9  149759.96   98344.148489

In [17]:
import pickle

In [18]:
pickle.dump(model, open('prediction_model.pkl', 'wb'))

In [24]:
trained_model = pickle.load(open('prediction_model.pkl','rb'))

In [26]:
print(trained_model.predict(X_test))

[113671.29227191  89670.79762675  76921.54451098  67071.7096238
 177373.64046375 173232.5405531   50750.15525607 100917.85478429
  54685.2692477   98344.14848891]
